### ISSUE TITLE
Ubuntu 1510 + node 0.12.9 - segmentation fault (v8 crashes)

### ISSUE THREAD

**Issue by devbnz** [jschyma/open_fints_js_client#17]
I tried to run the modified examples with my credentials using node v.12.9 on Ubuntu 15.10.

Everytime i run the demo, node/v8 crashed on my system during processing the data with segmentation fault.

![image](https://cloud.githubusercontent.com/assets/760988/12377728/9921a6b4-bd27-11e5-83da-535a207b14c3.png)

Solution was to upgrade to latest node version, 5.4.1.

Now it works perfect.

**Comment by jschyma** [comment]
Thanks for publishing the issue aswell as a solution.
Such an error when nodeJS crashes indicate an error in nodeJS.
Since using a newer version of nodeJS will work - I think they fixed this bug.
Therefor I think there is no need to fix something in the FinTS JS Library.
However for everyone expierencing the same error the solution is to Upgrade to a newer version. As @devbnz said, at least v5.4.1 will work.

For advanced search indexing:
Everyone expieriencing the following error in NodeJS on Ubuntu Prozent probably any other Linux or Unix the solution is to Update to a newer Version.

nodejs crashed with SIGSEGV in v8::internal::Factory::NewStringFromTwoByte()

This issue will be closed because it is allready solved.
